version: '3.8'

services:
  node1:
    build:
      context: ./Node/.
      dockerfile: Dockerfile
    container_name: Node1
    
    ports:
      - "5001:5000"
    environment:
      - IS_LEADER=${IS_LEADER:-true}
      - SERVER_NAME=MASTER
      - PORT=5001
      - UDP_PORT=5555
      - IP=127.0.0.2
      - DBNAME=mongoOne
      - name=Node1
    # depends_on:
    #   - mongoOne
    volumes:
      - data-volume1:/app
  node2:
    build:
      context: ./Node/.
      dockerfile: Dockerfile
    container_name: Node2
    
    ports:
    - "5002:5000"
    environment:
      - IS_LEADER=${IS_LEADER:-false}
      - SERVER_NAME=slaveOne
      - PORT=5002
      - UDP_PORT=5555
      - IP=127.0.0.3
      - DBNAME=mongoTwo
      - name=Node2
    # depends_on:
    #   - mongoOne
    volumes:
      - data-volume2:/app
  node3:
    build:
      context: ./Node/.
      dockerfile: Dockerfile
    container_name: Node3
    
    ports:
    - "5003:5000"
    environment:
      - IS_LEADER=${IS_LEADER:-false}
      - SERVER_NAME=slaveTwo
      - PORT=5003
      - UDP_PORT=5555
      - IP=127.0.0.4
      - DBNAME=mongoThree
      - name=Node3
    # depends_on:
    #   - mongoOne

    volumes:
      - data-volume3:/app
  node4:
    build:
      context: ./Node/.
      dockerfile: Dockerfile
    container_name: Node4
    ports:
    - "5004:5000"
    environment:
      - IS_LEADER=${IS_LEADER:-false}
      - SERVER_NAME=slaveThree
      - PORT=5004
      - UDP_PORT=5555
      - IP=127.0.0.5
      - DBNAME=mongoFour
      - name=Node4
    # depends_on:
    #   - mongoOne
    
    volumes:
      - data-volume4:/app
  node5:
    build:
      context: ./Node/.
      dockerfile: Dockerfile
    container_name: Node5
    ports:
    - "5005:5000"
    
    environment:
      - IS_LEADER=${IS_LEADER:-false}
      - SERVER_NAME=slaveFour
      - PORT=5005
      - UDP_PORT=5555
      - IP=127.0.0.6
      - DBNAME=mongoFive
      - name=Node5
    # depends_on:
    #   - mongoOne

    volumes:
      - data-volume5:/app

  controller:
      container_name: Controller
      build: Controller/.
      stdin_open: true



volumes:
    data-volume1:
    data-volume2:
    data-volume3:
    data-volume4:
    data-volume5: